"""modelos_sprint2_incidentes

Revision ID: 0bba04a56bf7
Revises: 98af1c090fc2
Create Date: 2026-05-14 07:22:40.219384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0bba04a56bf7"
down_revision: Union[str, Sequence[str], None] = "98af1c090fc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidentes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "accidente",
                "incidente",
                "cuasi_accidente",
                "condicion_insegura",
                name="tipoincidenteenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "severidad",
            sa.Enum(
                "sin_lesion",
                "leve",
                "moderada",
                "grave",
                "mortal",
                name="severidadenum",
            ),
            nullable=False,
        ),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("lugar", sa.String(length=300), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "borrador",
                "en_revision",
                "abierto",
                "en_investigacion",
                "cerrado",
                name="estadoincidenteenum",
            ),
            nullable=True,
        ),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("fecha_actualizacion", sa.DateTime(), nullable=True),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("trabajador_afectado_id", sa.UUID(), nullable=True),
        sa.Column("reportado_por_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reportado_por_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trabajador_afectado_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lesiones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tipo_lesion", sa.String(length=200), nullable=True),
        sa.Column("parte_afectada", sa.String(length=200), nullable=True),
        sa.Column("incapacidad_dias", sa.Integer(), nullable=True),
        sa.Column("incidente_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incidente_id"], ["incidentes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "testigos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("relato", sa.Text(), nullable=True),
        sa.Column("incidente_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incidente_id"], ["incidentes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testigos")
    op.drop_table("lesiones")
    op.drop_table("incidentes")
    # ### end Alembic commands ###
