"""ampliar_respuesta_dada_a_string500

Revision ID: 25c610b4119f
Revises: 7c80bdc74761
Create Date: 2026-06-09 20:25:11.316597

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25c610b4119f"
down_revision: Union[str, Sequence[str], None] = "7c80bdc74761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "respuestas_empleado",
        "respuesta_dada",
        existing_type=sa.VARCHAR(length=1),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "respuestas_empleado",
        "respuesta_dada",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
