"""feat: agregar rol admin y empresa_id nullable

Revision ID: 3fa9cc9dcd8d
Revises: 738b68b2392d
Create Date: 2026-05-20 07:41:45.473981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa9cc9dcd8d'
down_revision: Union[str, Sequence[str], None] = '738b68b2392d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
