"""add telefono foto_url to users

Revision ID: 437083986d0b
Revises: 318f5a54c35c
Create Date: 2026-06-09 08:54:34.117074

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "437083986d0b"
down_revision: Union[str, Sequence[str], None] = "318f5a54c35c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telefono", sa.String(length=30), nullable=True))
    op.add_column("users", sa.Column("foto_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "foto_url")
    op.drop_column("users", "telefono")
    # ### end Alembic commands ###
