"""add_usuario_id_to_notificaciones

Revision ID: 4b8c830edc2c
Revises: 25c610b4119f
Create Date: 2026-06-10 07:52:38.752537

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b8c830edc2c"
down_revision: Union[str, Sequence[str], None] = "25c610b4119f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notificaciones", sa.Column("usuario_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "notificaciones_usuario_id_fkey",
        "notificaciones",
        "users",
        ["usuario_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "notificaciones_usuario_id_fkey", "notificaciones", type_="foreignkey"
    )
    op.drop_column("notificaciones", "usuario_id")
    # ### end Alembic commands ###
