"""feat: tabla capacitacion_areas muchos a muchos

Revision ID: 63a28ad36845
Revises: 8a5039567707
Create Date: 2026-05-29 07:08:01.831113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63a28ad36845"
down_revision: Union[str, Sequence[str], None] = "8a5039567707"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capacitacion_areas",
        sa.Column("capacitacion_id", sa.UUID(), nullable=False),
        sa.Column("area_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["area_id"], ["areas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["capacitacion_id"], ["capacitaciones.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("capacitacion_id", "area_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("capacitacion_areas")
    # ### end Alembic commands ###
