"""seguridad_login_session_token

Revision ID: 738b68b2392d
Revises: 8d37122972c7
Create Date: 2026-05-20 06:16:59.484718

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "738b68b2392d"
down_revision: Union[str, Sequence[str], None] = "8d37122972c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "intentos_fallidos", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column("users", sa.Column("bloqueado_hasta", sa.DateTime(), nullable=True))
    op.add_column(
        "users", sa.Column("session_token", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "session_token")
    op.drop_column("users", "bloqueado_hasta")
    op.drop_column("users", "intentos_fallidos")
    # ### end Alembic commands ###
