"""modelos_sprint3_riesgos_auditorias

Revision ID: 8d37122972c7
Revises: c9025861d237
Create Date: 2026-05-14 19:56:15.087726

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d37122972c7"
down_revision: Union[str, Sequence[str], None] = "c9025861d237"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "peligros",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "fisico",
                "quimico",
                "biologico",
                "ergonomico",
                "psicosocial",
                "mecanico",
                "electrico",
                "locativo",
                "fenomeno_natural",
                name="tipopeligroenum",
            ),
            nullable=False,
        ),
        sa.Column("actividad", sa.String(length=300), nullable=True),
        sa.Column("trabajadores_expuestos", sa.Integer(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("area_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evaluaciones_riesgo",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("probabilidad", sa.Integer(), nullable=False),
        sa.Column("severidad", sa.Integer(), nullable=False),
        sa.Column(
            "nivel_riesgo",
            sa.Enum("bajo", "medio", "alto", "critico", name="nivelriesgoenum"),
            nullable=False,
        ),
        sa.Column("es_residual", sa.Boolean(), nullable=True),
        sa.Column("fecha_evaluacion", sa.DateTime(), nullable=True),
        sa.Column("peligro_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["peligro_id"], ["peligros.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auditorias",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("objetivos", sa.Text(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "planificada",
                "en_ejecucion",
                "completada",
                "cancelada",
                name="estadoauditoriaenum",
            ),
            nullable=True,
        ),
        sa.Column("fecha_programada", sa.DateTime(), nullable=False),
        sa.Column("fecha_ejecucion", sa.DateTime(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("area_id", sa.UUID(), nullable=True),
        sa.Column("auditor_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["auditor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "medidas_control",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "eliminacion",
                "sustitucion",
                "ingenieria",
                "administrativo",
                "epp",
                name="tipocontrolenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum(
                "planificada", "en_ejecucion", "completada", name="estadocontrolenum"
            ),
            nullable=True,
        ),
        sa.Column("evidencia", sa.Text(), nullable=True),
        sa.Column("fecha_limite", sa.DateTime(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("peligro_id", sa.UUID(), nullable=False),
        sa.Column("responsable_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["peligro_id"],
            ["peligros.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsable_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hallazgos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column(
            "clasificacion",
            sa.Enum(
                "conformidad",
                "no_conformidad_menor",
                "no_conformidad_mayor",
                "observacion",
                name="clasificacionhallazgoenum",
            ),
            nullable=False,
        ),
        sa.Column("evidencia", sa.Text(), nullable=True),
        sa.Column("recomendacion", sa.Text(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("auditoria_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["auditoria_id"], ["auditorias.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "no_conformidades",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("abierta", "en_proceso", "cerrada", "vencida", name="estadoncenum"),
            nullable=True,
        ),
        sa.Column("evidencia_cierre", sa.Text(), nullable=True),
        sa.Column("fecha_limite", sa.DateTime(), nullable=False),
        sa.Column("fecha_cierre", sa.DateTime(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("hallazgo_id", sa.UUID(), nullable=False),
        sa.Column("responsable_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["hallazgo_id"], ["hallazgos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["responsable_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("no_conformidades")
    op.drop_table("hallazgos")
    op.drop_table("medidas_control")
    op.drop_table("auditorias")
    op.drop_table("evaluaciones_riesgo")
    op.drop_table("peligros")
    # ### end Alembic commands ###
