"""sprint_4_agregar_refresh_token

Revision ID: a504abdcac24
Revises: b5d57e4afb69
Create Date: 2026-05-27 22:15:47.892535

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a504abdcac24"
down_revision: Union[str, Sequence[str], None] = "b5d57e4afb69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("refresh_token", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("refresh_token_expira", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token_expira")
    op.drop_column("users", "refresh_token")
    # ### end Alembic commands ###
