"""sprint_4_agregar_debe_cambiar_password

Revision ID: b5d57e4afb69
Revises: 3fa9cc9dcd8d
Create Date: 2026-05-27 22:06:48.998305

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5d57e4afb69"
down_revision: Union[str, Sequence[str], None] = "3fa9cc9dcd8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "debe_cambiar_password",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "debe_cambiar_password")
    # ### end Alembic commands ###
