"""modelos_capacitaciones

Revision ID: c9025861d237
Revises: d896676c7a0a
Create Date: 2026-05-14 09:45:06.186111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9025861d237"
down_revision: Union[str, Sequence[str], None] = "d896676c7a0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capacitaciones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=300), nullable=False),
        sa.Column("objetivos", sa.Text(), nullable=True),
        sa.Column("duracion_horas", sa.Integer(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("facilitador_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facilitador_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sesiones_capacitacion",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("lugar", sa.String(length=300), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("capacitacion_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["capacitacion_id"], ["capacitaciones.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asistencias",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=True),
        sa.Column("fecha_registro", sa.DateTime(), nullable=True),
        sa.Column("sesion_id", sa.UUID(), nullable=False),
        sa.Column("empleado_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["empleado_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sesion_id"], ["sesiones_capacitacion.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evaluaciones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=300), nullable=False),
        sa.Column("puntaje_minimo", sa.Integer(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("sesion_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sesion_id"], ["sesiones_capacitacion.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preguntas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("opcion_a", sa.String(length=500), nullable=False),
        sa.Column("opcion_b", sa.String(length=500), nullable=False),
        sa.Column("opcion_c", sa.String(length=500), nullable=False),
        sa.Column("opcion_d", sa.String(length=500), nullable=False),
        sa.Column("respuesta_correcta", sa.String(length=1), nullable=False),
        sa.Column("evaluacion_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluacion_id"], ["evaluaciones.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "respuestas_empleado",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("respuesta_dada", sa.String(length=1), nullable=False),
        sa.Column("es_correcta", sa.Boolean(), nullable=True),
        sa.Column("puntaje_final", sa.Integer(), nullable=True),
        sa.Column("aprobado", sa.Boolean(), nullable=True),
        sa.Column("fecha_respuesta", sa.DateTime(), nullable=True),
        sa.Column("evaluacion_id", sa.UUID(), nullable=False),
        sa.Column("empleado_id", sa.UUID(), nullable=False),
        sa.Column("pregunta_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["empleado_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluacion_id"],
            ["evaluaciones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pregunta_id"],
            ["preguntas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("respuestas_empleado")
    op.drop_table("preguntas")
    op.drop_table("evaluaciones")
    op.drop_table("asistencias")
    op.drop_table("sesiones_capacitacion")
    op.drop_table("capacitaciones")
    # ### end Alembic commands ###
