"""investigacion_y_acciones_correctivas

Revision ID: d896676c7a0a
Revises: 0bba04a56bf7
Create Date: 2026-05-14 07:27:37.031373

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d896676c7a0a"
down_revision: Union[str, Sequence[str], None] = "0bba04a56bf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acciones_correctivas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("evidencia", sa.Text(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "planificada",
                "en_ejecucion",
                "completada",
                "vencida",
                name="estadoaccionenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "prioridad",
            sa.Enum("alta", "media", "baja", name="prioridadaccionenum"),
            nullable=True,
        ),
        sa.Column("fecha_limite", sa.DateTime(), nullable=False),
        sa.Column("fecha_cierre", sa.DateTime(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("incidente_id", sa.UUID(), nullable=False),
        sa.Column("responsable_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incidente_id"],
            ["incidentes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsable_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "investigaciones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("metodo_analisis", sa.String(length=100), nullable=True),
        sa.Column("causas_inmediatas", sa.Text(), nullable=True),
        sa.Column("causas_basicas", sa.Text(), nullable=True),
        sa.Column("factores_contribuyentes", sa.Text(), nullable=True),
        sa.Column("descripcion_evento", sa.Text(), nullable=True),
        sa.Column("lecciones_aprendidas", sa.Text(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
        sa.Column("incidente_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incidente_id"], ["incidentes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("investigaciones")
    op.drop_table("acciones_correctivas")
    # ### end Alembic commands ###
