"""sprint_4_agregar_indices_criticos

Revision ID: f33fd7b158a0
Revises: a504abdcac24
Create Date: 2026-05-27 22:24:17.722158

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f33fd7b158a0"
down_revision: Union[str, Sequence[str], None] = "a504abdcac24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_acciones_incidente_estado",
        "acciones_correctivas",
        ["incidente_id", "estado"],
        unique=False,
    )
    op.create_index(
        "ix_incidentes_empresa_estado",
        "incidentes",
        ["empresa_id", "estado"],
        unique=False,
    )
    op.create_index(
        "ix_users_empresa_activo", "users", ["empresa_id", "activo"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_empresa_activo", table_name="users")
    op.drop_index("ix_incidentes_empresa_estado", table_name="incidentes")
    op.drop_index("ix_acciones_incidente_estado", table_name="acciones_correctivas")
    # ### end Alembic commands ###
